# Generated by Django 5.0.1 on 2024-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Electronicos', 'Electronicos'), ('Aseo', 'Aseo'), ('Comestibles', 'Comestibles')], max_length=30, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
