# Generated by Django 5.0.1 on 2024-01-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
