# Generated by Django 5.0.1 on 2024-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_perfil_apellido_perfil_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
