# Generated by Django 5.0.1 on 2024-02-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_perfil_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
